name: quiz_anac
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  flutter_modular: ^6.3.2
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  smooth_page_indicator: ^1.1.0
  equatable: ^2.0.5

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/image/
    - assets/data/data.json
